on:
  push:
    paths:
      - '.github/workflows/run.yml'
defaults:
  run:
    shell: bash

name: update core
jobs:
  backup:
      runs-on: ubuntu-20.04
      steps:

        - name: Checkout
          uses: actions/checkout@v2.3.4

        - name: Set variables
          run: |
            echo "VERSION=v98.0.4758.80-2" >> $GITHUB_ENV
            echo "TAGS=$(wget -qO- https://api.github.com/repos/bolucat/peace/tags | grep 'name' | cut -d\" -f4 | head -1)" >> $GITHUB_ENV
          shell: bash

        - name: Updating
          run: |
            rm -rfv windows/naive.exe
            wget -O windows/naive.exe https://github.com/bolucat/peace/releases/download/${{ env.TAGS }}/naive-windows-amd64.exe
            # Commit
            git config --local user.name "github-action[bot]"
            git config --local user.email "${{ secrets.EMAIL }}"
            git add .
            git commit -am "Update Core to ${{ env.VERSION }}"
            
        - name: Push Changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: ${{ github.ref }}
